### ISSUE TITLE
cannot download node dependencies from @bifravst github repo

### ISSUE THREAD

**Issue by cmedianu** [bifravst/azure#11]
Hi there,

I am trying to set up this project, but npm ci fails because the node dependencies are not public. Could you make them public?

126 verbose stack Error: Unable to authenticate, need: Basic realm="GitHub Package Registry"
126 verbose stack     at /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:94:17
126 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
127 verbose statusCode 401
128 verbose pkgid @bifravst/random-words@4.1.3

118 http fetch GET 401 https://npm.pkg.github.com/download/@bifravst/random-words/4.1.3/cb65fd933409e54c275d293b28c7d0930049cf5373872e6034e0d9c22b0509b2 300ms
120 http fetch GET 401 https://npm.pkg.github.com/download/@bifravst/device-ui-server/1.1.2/654adce77161def5bc6b29f0602af51a9776bf02acba164bd775cf27de286fa4 326ms
121 http fetch GET 401 https://npm.pkg.github.com/download/@bifravst/code-style/6.0.2/c20a2a562cc57693978c6ec5f943ea10a4e36bdfe70d10c4e0223c9bc5f19f12 278ms

Thanks!

**Comment by cmedianu** [comment]
And the answer is here:
https://bifravst.gitbook.io/bifravst/v/saga/guides/githubregistry
:)
